/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftSol from './NFT.sol/index.js';
export type { nftSol };
import type * as counterSol from './counter.sol/index.js';
export type { counterSol };
import type * as marketplaceSol from './marketplace.sol/index.js';
export type { marketplaceSol };
export * as factories from './factories/index.js';
export type { Counter } from './counter.sol/Counter.js';
export { Counter__factory } from './factories/counter.sol/Counter__factory.js';
export type { Marketplace } from './marketplace.sol/Marketplace.js';
export { Marketplace__factory } from './factories/marketplace.sol/Marketplace__factory.js';
export type { PortfolioNFT } from './NFT.sol/PortfolioNFT.js';
export { PortfolioNFT__factory } from './factories/NFT.sol/PortfolioNFT__factory.js';